spring:
  application:
    name: share-park-zuul

server:
  port: 8769

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
# zuul:
 # routes:
  # api-a:
  #   path: /course/**
  #   serviceId: hi-spring-cloud-course
  # api-b:
  #   path: /member/**
  #   serviceId: hi-spring-cloud-member

