spring:
  application:
    name: share-park-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/deninising/share-parking
          search-paths: respo
          username: 906086497@qq.com
          password: liaopeng666

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
